import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  throw new Error("DATABASE_URL is not set");
}

const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

function slugify(text: string): string {
  return text
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-");
}

const recipes = [
  // === SNÍDANĚ ===
  {
    name: "Ovesná kaše s jablkem a medem",
    description: "Teplá a sytá snídaně z ovesných vloček s čerstvým jablkem a kapkou medu.",
    mealTypes: "snidane",
    ingredients: [
      { name: "Ovesné vločky", amount: 80, unit: "g" },
      { name: "Mléko", amount: 200, unit: "ml" },
      { name: "Voda", amount: 100, unit: "ml" },
      { name: "Jablko", amount: 1, unit: "ks" },
      { name: "Med", amount: 1, unit: "lžička" },
      { name: "Máslo", amount: 5, unit: "g" },
    ],
    instructions: [
      "Ovesné vločky dejte do kastrůlku, přidejte mléko a vodu.",
      "Vařte na mírném ohni asi 5 minut za stálého míchání, dokud kaše nezhoustne.",
      "Jablko oloupejte a nastrouhejte nebo nakrájejte na malé kousky.",
      "Přimíchejte jablko do kaše, přidejte máslo a promíchejte.",
      "Přendejte do misky, pokapejte medem a podávejte ihned.",
    ],
    prepTime: 5,
    cookTime: 7,
    servings: 1,
    tags: "snidane,bezlepkove-alternativa,vegetarianke",
  },
  {
    name: "Míchaná vejce s pažitkou",
    description: "Klasická snídaně z čerstvě míchaných vajec dochucená čerstvou pažitkou.",
    mealTypes: "snidane",
    ingredients: [
      { name: "Vejce", amount: 3, unit: "ks" },
      { name: "Máslo", amount: 15, unit: "g" },
      { name: "Pažitka čerstvá", amount: 10, unit: "g" },
      { name: "Sůl", amount: 1, unit: "špetka" },
    ],
    instructions: [
      "Vejce rozšlehejte vidličkou, přidejte sůl.",
      "Na pánvi rozpusťte máslo na mírném ohni.",
      "Přilijte vejce a pomalu je míchejte stěrkou, dokud neztuhnou do krémova.",
      "Posypte nakrájenou pažitkou a ihned podávejte.",
    ],
    prepTime: 3,
    cookTime: 4,
    servings: 1,
    tags: "snidane,rychle,bezlepkove",
  },
  {
    name: "Rýžová kaše s hruškou",
    description: "Jemná rýžová kaše s vařenou hruškou, vhodná i pro citlivý žaludek.",
    mealTypes: "snidane",
    ingredients: [
      { name: "Rýžová mouka", amount: 50, unit: "g" },
      { name: "Mléko", amount: 250, unit: "ml" },
      { name: "Hruška", amount: 1, unit: "ks" },
      { name: "Med", amount: 1, unit: "lžička" },
      { name: "Máslo", amount: 5, unit: "g" },
    ],
    instructions: [
      "Hrušku oloupejte, nakrájejte na kostičky a krátce poduste na másle.",
      "Rýžovou mouku smíchejte s trochou studeného mléka.",
      "Zbytek mléka zahřejte, za míchání přidejte rýžovou mouku.",
      "Vařte 5 minut do zhoustnutí, přidejte med.",
      "Podávejte s hruškou navrchu.",
    ],
    prepTime: 5,
    cookTime: 8,
    servings: 1,
    tags: "snidane,bezlepkove,laktózové",
  },
  {
    name: "Palačinky s tvarohem a ovocem",
    description: "Lehké palačinky plněné sladkým tvarohem a čerstvým ovocem.",
    mealTypes: "snidane,dessert",
    ingredients: [
      { name: "Hladká mouka", amount: 100, unit: "g" },
      { name: "Vejce", amount: 1, unit: "ks" },
      { name: "Mléko", amount: 200, unit: "ml" },
      { name: "Máslo", amount: 20, unit: "g" },
      { name: "Tvaroh", amount: 150, unit: "g" },
      { name: "Med", amount: 2, unit: "lžičky" },
      { name: "Jablko nebo hruška", amount: 1, unit: "ks" },
    ],
    instructions: [
      "Z mouky, vejce, mléka a 10 g másla připravte hladké těsto, nechte 10 minut odpočinout.",
      "Smažte tenké palačinky na másle.",
      "Tvaroh smíchejte s medem.",
      "Ovoce oloupejte a nakrájejte na plátky nebo kostičky.",
      "Každou palačinku naplňte tvarohem a ovocem, přeložte.",
    ],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    tags: "snidane,dessert,vegetarianke",
  },
  {
    name: "Pohankové lívanečky",
    description: "Bezlepkové pohankové lívanečky, výborné s javorovým sirupem nebo medem.",
    mealTypes: "snidane",
    ingredients: [
      { name: "Pohankové kroupy (vařené)", amount: 150, unit: "g" },
      { name: "Vejce", amount: 2, unit: "ks" },
      { name: "Mléko", amount: 50, unit: "ml" },
      { name: "Kokosový olej", amount: 15, unit: "ml" },
      { name: "Med nebo javorový sirup", amount: 2, unit: "lžičky" },
      { name: "Jedlá soda", amount: 0.5, unit: "lžičky" },
      { name: "Sůl", amount: 1, unit: "špetka" },
    ],
    instructions: [
      "Vařené pohankové kroupy rozmixujte nebo rozmačkejte vidličkou.",
      "Smíchejte s vejci, mlékem, medem, jedlou sodou a solí.",
      "Na pánvi zahřejte kokosový olej.",
      "Lžicí klaďte těsto na pánev a smažte lívanečky 2–3 minuty z každé strany.",
      "Podávejte s medem nebo javorovým sirupem.",
    ],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    tags: "snidane,bezlepkove,vegetarianke",
  },
  {
    name: "Toast s avokádem a vejcem (verze bez avokáda)",
    description: "Toastový chléb s máslem, tvarohem a vařeným vejcem — bezpečná varianta oblíbeného jídla.",
    mealTypes: "snidane",
    ingredients: [
      { name: "Celozrnný toast", amount: 2, unit: "plátky" },
      { name: "Máslo", amount: 20, unit: "g" },
      { name: "Tvaroh", amount: 80, unit: "g" },
      { name: "Vejce", amount: 2, unit: "ks" },
      { name: "Pažitka", amount: 5, unit: "g" },
      { name: "Sůl a pepř", amount: 1, unit: "špetka" },
    ],
    instructions: [
      "Vejce uvařte na tvrdo (8 minut v osolené vodě).",
      "Toasty opečte a potřete máslem.",
      "Tvaroh okořeňte solí a pepřem, rozetřete na toasty.",
      "Vejce oloupejte, nakrájejte na plátky a naskládejte navrch.",
      "Posypte čerstvou pažitkou.",
    ],
    prepTime: 5,
    cookTime: 10,
    servings: 1,
    tags: "snidane,rychle",
  },
  {
    name: "Jogurt z čerstvého mléka s ovocem (nízkotučný)",
    description: "Domácí řídký jogurt z pasterizovaného mléka s čerstvým ovocem. Pozor: jogurt je pro nízkohistaminovou dietu hraniční — sledujte vlastní toleranci.",
    mealTypes: "snidane,svacina",
    ingredients: [
      { name: "Tvaroh", amount: 150, unit: "g" },
      { name: "Mléko", amount: 50, unit: "ml" },
      { name: "Hruška nebo jablko", amount: 1, unit: "ks" },
      { name: "Med", amount: 1, unit: "lžička" },
      { name: "Granola bez ořechů", amount: 30, unit: "g" },
    ],
    instructions: [
      "Tvaroh rozmíchejte s mlékem do hladka.",
      "Ovoce nakrájejte na malé kousky.",
      "Do misky dejte tvarohovou směs, navrch ovoce.",
      "Pokapejte medem a posypte granolou.",
    ],
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    tags: "snidane,svacina,studene,rychle",
  },
  // === OBĚD ===
  {
    name: "Kuřecí vývar se zeleninou",
    description: "Hřejivý domácí kuřecí vývar s kořenovou zeleninou, ideální pro studené dny nebo jako základ polévky.",
    mealTypes: "obed",
    ingredients: [
      { name: "Kuřecí hřbet nebo krk", amount: 500, unit: "g" },
      { name: "Mrkev", amount: 2, unit: "ks" },
      { name: "Petržel (kořen)", amount: 1, unit: "ks" },
      { name: "Celer (malý kus)", amount: 50, unit: "g" },
      { name: "Cibule", amount: 1, unit: "ks" },
      { name: "Sůl", amount: 1, unit: "lžička" },
      { name: "Bobkový list", amount: 2, unit: "ks" },
      { name: "Nové koření", amount: 3, unit: "ks" },
      { name: "Petrželová nať", amount: 1, unit: "hrst" },
    ],
    instructions: [
      "Maso opláchněte, vložte do hrnce a zalijte 1,5 l studené vody.",
      "Přiveďte pomalu k varu, sbírejte pěnu.",
      "Přidejte očistenou celou zeleninu, koření a sůl.",
      "Vařte na mírném ohni 1,5 hodiny.",
      "Vývar přeceďte, mrkev a petrželový kořen nakrájejte na kolečka a vraťte do vývaru.",
      "Podávejte posypané čerstvou petrželí.",
    ],
    prepTime: 15,
    cookTime: 90,
    servings: 4,
    tags: "obed,polevka,bezlepkove",
  },
  {
    name: "Pečené kuřecí prso s brambory",
    description: "Šťavnaté pečené kuřecí prso s bylinkami, podávané s pečenými bramborami.",
    mealTypes: "obed,vecere",
    ingredients: [
      { name: "Kuřecí prso", amount: 400, unit: "g" },
      { name: "Brambory", amount: 500, unit: "g" },
      { name: "Olivový olej", amount: 30, unit: "ml" },
      { name: "Česnek", amount: 2, unit: "stroužky" },
      { name: "Rozmarýn čerstvý", amount: 2, unit: "větvičky" },
      { name: "Tymián čerstvý", amount: 2, unit: "větvičky" },
      { name: "Sůl", amount: 1, unit: "lžička" },
    ],
    instructions: [
      "Troubu předehřejte na 200 °C.",
      "Brambory oloupejte a nakrájejte na čtvrtky, smíchejte s olejem, solí a bylinkami.",
      "Kuřecí prso potřete olejem, osolte, přidejte česnek a rozmarýn.",
      "Brambory a maso dejte na plech.",
      "Pečte 35–40 minut, dokud maso není zlatavé a brambory měkké.",
    ],
    prepTime: 15,
    cookTime: 40,
    servings: 2,
    tags: "obed,vecere,bezlepkove",
  },
  {
    name: "Rýže s dušenou zeleninou a vejcem",
    description: "Rychlá a výživná mísa s vařenou rýží, dušenou zeleninou a smažným vejcem.",
    mealTypes: "obed,vecere",
    ingredients: [
      { name: "Rýže jasmínová", amount: 150, unit: "g" },
      { name: "Cuketa", amount: 1, unit: "ks" },
      { name: "Mrkev", amount: 1, unit: "ks" },
      { name: "Brokolice", amount: 150, unit: "g" },
      { name: "Vejce", amount: 2, unit: "ks" },
      { name: "Olivový olej", amount: 20, unit: "ml" },
      { name: "Sůl", amount: 1, unit: "lžička" },
      { name: "Česnek", amount: 1, unit: "stroužek" },
    ],
    instructions: [
      "Uvařte rýži dle návodu.",
      "Zeleninu nakrájejte na kousky.",
      "Na pánvi rozehřejte olej, přidejte česnek a zeleninu.",
      "Duste 8–10 minut do měkka, osolte.",
      "Zvlášť orestujte nebo osmažte vajíčka.",
      "Podávejte rýži se zeleninou a vejcem.",
    ],
    prepTime: 10,
    cookTime: 20,
    servings: 2,
    tags: "obed,vecere,bezlepkove,vegetarianke",
  },
  {
    name: "Krůtí karbanátky s bramborovou kaší",
    description: "Šťavnaté krůtí karbanátky s jemnou bramborovou kaší — klasika na nízkohistaminové dietě.",
    mealTypes: "obed,vecere",
    ingredients: [
      { name: "Mleté krůtí maso", amount: 400, unit: "g" },
      { name: "Cibule", amount: 1, unit: "ks" },
      { name: "Vejce", amount: 1, unit: "ks" },
      { name: "Hladká mouka", amount: 2, unit: "lžíce" },
      { name: "Brambory", amount: 600, unit: "g" },
      { name: "Mléko", amount: 100, unit: "ml" },
      { name: "Máslo", amount: 30, unit: "g" },
      { name: "Sůl, pepř", amount: 1, unit: "špetka" },
      { name: "Olej na smažení", amount: 30, unit: "ml" },
    ],
    instructions: [
      "Cibuli najemno nakrájejte nebo nastrouhejte.",
      "Smíchejte mleté maso, cibuli, vejce, mouku, sůl a pepř.",
      "Tvarujte karbanátky a smažte na oleji ze dvou stran do zlatova (asi 6 minut z každé strany).",
      "Mezitím uvařte brambory, slijte vodu, přidejte máslo a teplé mléko a rozmašírujte.",
      "Podávejte karbanátky s bramborovou kaší.",
    ],
    prepTime: 20,
    cookTime: 25,
    servings: 3,
    tags: "obed,vecere",
  },
  {
    name: "Polévka z květáku",
    description: "Krémová polévka z pečeného květáku bez smetany — jemná a výživná.",
    mealTypes: "obed",
    ingredients: [
      { name: "Květák", amount: 1, unit: "ks (cca 700 g)" },
      { name: "Cibule", amount: 1, unit: "ks" },
      { name: "Česnek", amount: 2, unit: "stroužky" },
      { name: "Kuřecí nebo zeleninový vývar", amount: 700, unit: "ml" },
      { name: "Máslo", amount: 20, unit: "g" },
      { name: "Olivový olej", amount: 20, unit: "ml" },
      { name: "Sůl, pepř", amount: 1, unit: "špetka" },
      { name: "Petrželová nať", amount: 1, unit: "hrst" },
    ],
    instructions: [
      "Troubu předehřejte na 200 °C. Květák rozdělte na růžičky, polijte olejem, osolte a pečte 25 minut.",
      "Cibuli a česnek osmažte na másle v hrnci.",
      "Přidejte pečený květák a vývar.",
      "Vařte 10 minut, pak rozmixujte dohladka.",
      "Dosolte, podávejte posypané petrželí.",
    ],
    prepTime: 10,
    cookTime: 40,
    servings: 3,
    tags: "obed,polevka,bezlepkove,vegetarianke",
  },
  {
    name: "Těstovinový salát s kuřecím masem",
    description: "Lehký těstovinový salát s grilovaným kuřecím masem, okurkou a olivovým olejem.",
    mealTypes: "obed",
    ingredients: [
      { name: "Těstoviny (fusilli nebo penne)", amount: 200, unit: "g" },
      { name: "Kuřecí prso", amount: 200, unit: "g" },
      { name: "Okurka", amount: 0.5, unit: "ks" },
      { name: "Červená paprika (malé množství)", amount: 0.5, unit: "ks" },
      { name: "Olivový olej", amount: 30, unit: "ml" },
      { name: "Česnek", amount: 1, unit: "stroužek" },
      { name: "Sůl, pepř", amount: 1, unit: "špetka" },
      { name: "Čerstvá bazalka", amount: 1, unit: "hrst" },
    ],
    instructions: [
      "Uvařte těstoviny al dente, slijte a proplachněte studenou vodou.",
      "Kuřecí prso osolte, osmažte nebo ugrilujte a nakrájejte na proužky.",
      "Okurku a papriku nakrájejte na kostičky.",
      "Vše smíchejte, polejte olejem, přidejte prolisovaný česnek, sůl a pepř.",
      "Dozdobte čerstvou bazalkou.",
    ],
    prepTime: 15,
    cookTime: 15,
    servings: 2,
    tags: "obed,studene,rychle",
  },
  {
    name: "Zapečené brambory se sýrem a brokolici",
    description: "Výdatné zapečené brambory plněné měkkou brokolici a čerstvým sýrem.",
    mealTypes: "obed,vecere",
    ingredients: [
      { name: "Brambory velké", amount: 4, unit: "ks" },
      { name: "Brokolice", amount: 200, unit: "g" },
      { name: "Tvaroh nebo ricotta", amount: 100, unit: "g" },
      { name: "Máslo", amount: 20, unit: "g" },
      { name: "Sůl, pepř", amount: 1, unit: "špetka" },
      { name: "Pažitka", amount: 10, unit: "g" },
    ],
    instructions: [
      "Troubu předehřejte na 200 °C. Brambory propíchněte vidličkou a pečte 50–60 minut.",
      "Brokolici uvařte do měkka a rozmačkejte vidličkou.",
      "Uvařené brambory rozkrojte, vydlabněte část dužiny.",
      "Smíchejte bramborovou dužinu s brokolici, tvarohem, máslem, solí a pepřem.",
      "Naplňte brambory, vraťte do trouby a zapečte 10 minut.",
      "Podávejte posypané pažitkou.",
    ],
    prepTime: 15,
    cookTime: 70,
    servings: 2,
    tags: "obed,vecere,vegetarianke,bezlepkove",
  },
  {
    name: "Quinoa s pečenou zeleninou",
    description: "Výživná quinoa s barevnou pečenou zeleninou a bylinkovým dresinkem.",
    mealTypes: "obed,vecere",
    ingredients: [
      { name: "Quinoa", amount: 150, unit: "g" },
      { name: "Cuketa", amount: 1, unit: "ks" },
      { name: "Mrkev", amount: 2, unit: "ks" },
      { name: "Červená řepa čerstvá", amount: 1, unit: "ks" },
      { name: "Olivový olej", amount: 40, unit: "ml" },
      { name: "Česnek", amount: 2, unit: "stroužky" },
      { name: "Tymián čerstvý", amount: 2, unit: "větvičky" },
      { name: "Sůl, pepř", amount: 1, unit: "špetka" },
      { name: "Čerstvá petrželová nať", amount: 1, unit: "hrst" },
    ],
    instructions: [
      "Quinoa: opláchněte, uvařte ve dvojnásobném množství osolené vody 15 minut.",
      "Zeleninu nakrájejte na kostky, smíchejte s olejem, česnekem a tymiánem.",
      "Pečte při 200 °C po dobu 25 minut.",
      "Smíchejte quinoa s pečenou zeleninou.",
      "Posypte čerstvou petrželí, dochuťte solí.",
    ],
    prepTime: 15,
    cookTime: 30,
    servings: 2,
    tags: "obed,vecere,bezlepkove,vegetarianke",
  },
  {
    name: "Polévka z mrkve a zázvoru",
    description: "Jemná krémová polévka z mrkve s trochou čerstvého zázvoru.",
    mealTypes: "obed",
    ingredients: [
      { name: "Mrkev", amount: 500, unit: "g" },
      { name: "Cibule", amount: 1, unit: "ks" },
      { name: "Čerstvý zázvor", amount: 10, unit: "g" },
      { name: "Zeleninový vývar", amount: 700, unit: "ml" },
      { name: "Kokosové mléko", amount: 100, unit: "ml" },
      { name: "Olivový olej", amount: 20, unit: "ml" },
      { name: "Sůl", amount: 1, unit: "lžička" },
    ],
    instructions: [
      "Mrkev oloupejte a nakrájejte na kolečka. Cibuli nakrájejte na kostky.",
      "Na oleji osmažte cibuli, přidejte mrkev a nastrouhejte zázvor.",
      "Zalijte vývarem a vařte 20 minut, dokud mrkev nezměkne.",
      "Rozmixujte dohladka, přilijte kokosové mléko.",
      "Osolte a podávejte.",
    ],
    prepTime: 10,
    cookTime: 25,
    servings: 3,
    tags: "obed,polevka,bezlepkove,vegetarianke",
  },
  {
    name: "Vaječná omeleta se zeleninou",
    description: "Rychlá omeleta plněná sezónní zeleninou — ideální oběd nebo lehká večeře.",
    mealTypes: "obed,vecere",
    ingredients: [
      { name: "Vejce", amount: 3, unit: "ks" },
      { name: "Cuketa", amount: 0.5, unit: "ks" },
      { name: "Paprika (červená, malé množství)", amount: 0.5, unit: "ks" },
      { name: "Pažitka", amount: 10, unit: "g" },
      { name: "Máslo", amount: 10, unit: "g" },
      { name: "Sůl, pepř", amount: 1, unit: "špetka" },
    ],
    instructions: [
      "Zeleninu nakrájejte na malé kostičky a orestujte na másle 4 minuty.",
      "Vejce rozšlehejte, osolte a opepřete.",
      "Přilijte vejce na zeleninu a nechte otuhnout.",
      "Opatrně omeletu přeložte a obraťte.",
      "Posypte pažitkou a podávejte.",
    ],
    prepTime: 8,
    cookTime: 8,
    servings: 1,
    tags: "obed,vecere,bezlepkove,vegetarianke,rychle",
  },
  {
    name: "Jehněčí ragú s rýží",
    description: "Jemné jehněčí ragú s kořenovou zeleninou, podávané s rýží.",
    mealTypes: "obed,vecere",
    ingredients: [
      { name: "Jehněčí maso (kýta nebo plec)", amount: 400, unit: "g" },
      { name: "Mrkev", amount: 2, unit: "ks" },
      { name: "Celer kořen", amount: 100, unit: "g" },
      { name: "Cibule", amount: 1, unit: "ks" },
      { name: "Kuřecí vývar", amount: 300, unit: "ml" },
      { name: "Olivový olej", amount: 20, unit: "ml" },
      { name: "Rozmarýn", amount: 1, unit: "větvička" },
      { name: "Sůl, pepř", amount: 1, unit: "špetka" },
      { name: "Rýže", amount: 200, unit: "g" },
    ],
    instructions: [
      "Maso nakrájejte na kostky a orestujte na oleji dozlatova.",
      "Přidejte nakrájenou zeleninu a cibuli, restujte 5 minut.",
      "Zalijte vývarem, přidejte rozmarýn.",
      "Duste pod pokličkou 60–70 minut na mírném ohni.",
      "Uvařte rýži a podávejte ragú přelité na rýži.",
    ],
    prepTime: 20,
    cookTime: 75,
    servings: 3,
    tags: "obed,vecere,bezlepkove",
  },
  {
    name: "Zeleninová polévka s pohankou",
    description: "Hustá a výživná polévka plná zeleniny a pohankových krup.",
    mealTypes: "obed",
    ingredients: [
      { name: "Brambory", amount: 2, unit: "ks" },
      { name: "Mrkev", amount: 2, unit: "ks" },
      { name: "Petržel kořen", amount: 1, unit: "ks" },
      { name: "Pórek", amount: 0.5, unit: "ks" },
      { name: "Pohankové kroupy", amount: 50, unit: "g" },
      { name: "Zeleninový vývar", amount: 1, unit: "l" },
      { name: "Olivový olej", amount: 15, unit: "ml" },
      { name: "Sůl, pepř", amount: 1, unit: "špetka" },
      { name: "Čerstvá petrželová nať", amount: 1, unit: "hrst" },
    ],
    instructions: [
      "Zeleninu nakrájejte na kostičky.",
      "Na oleji osmažte pórek, přidejte zeleninu.",
      "Zalijte vývarem a přidejte pohanku.",
      "Vařte 25 minut do změknutí zeleniny.",
      "Dosolte, podávejte s čerstvou petrželí.",
    ],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    tags: "obed,polevka,bezlepkove,vegetarianke",
  },
  {
    name: "Pečený losos s citronovou zeleninou",
    description: "Čerstvý losos pečený s citronovou šťávou (malé množství) a bylinkami.",
    mealTypes: "obed,vecere",
    ingredients: [
      { name: "Losos (čerstvý nebo zmražený)", amount: 400, unit: "g" },
      { name: "Cuketa", amount: 1, unit: "ks" },
      { name: "Mrkev", amount: 1, unit: "ks" },
      { name: "Olivový olej", amount: 20, unit: "ml" },
      { name: "Citronová šťáva (malé množství)", amount: 10, unit: "ml" },
      { name: "Kopr čerstvý", amount: 10, unit: "g" },
      { name: "Sůl", amount: 1, unit: "lžička" },
    ],
    instructions: [
      "Troubu předehřejte na 180 °C.",
      "Zeleninu nakrájejte na proužky, polijte olejem a osolte.",
      "Lososa položte na pečicí papír, pokapejte olejem a citronovou šťávou.",
      "Rybě dejte zeleninu kolem sebe.",
      "Pečte 18–20 minut.",
      "Podávejte posypané čerstvým koprem.",
    ],
    prepTime: 10,
    cookTime: 20,
    servings: 2,
    tags: "obed,vecere,bezlepkove",
  },
  {
    name: "Čočková polévka s mrkví",
    description: "Hustá a hřejivá čočková polévka s mrkví — výborný zdroj bílkovin.",
    mealTypes: "obed",
    ingredients: [
      { name: "Červená čočka", amount: 200, unit: "g" },
      { name: "Mrkev", amount: 2, unit: "ks" },
      { name: "Cibule", amount: 1, unit: "ks" },
      { name: "Česnek", amount: 2, unit: "stroužky" },
      { name: "Kurkuma", amount: 0.5, unit: "lžičky" },
      { name: "Olivový olej", amount: 20, unit: "ml" },
      { name: "Zeleninový vývar", amount: 800, unit: "ml" },
      { name: "Sůl", amount: 1, unit: "lžička" },
      { name: "Čerstvá petrželová nať", amount: 1, unit: "hrst" },
    ],
    instructions: [
      "Cibuli a česnek osmažte na oleji.",
      "Přidejte nakrájenou mrkev a kurkumu, restujte 3 minuty.",
      "Přidejte oplakanou čočku a zalijte vývarem.",
      "Vařte 20 minut na mírném ohni, dokud čočka nezměkne.",
      "Rozmixujte část polévky pro hustší konzistenci.",
      "Dosolte a podávejte s petrželí.",
    ],
    prepTime: 10,
    cookTime: 25,
    servings: 3,
    tags: "obed,polevka,bezlepkove,vegetarianke",
  },
  // === VEČEŘE ===
  {
    name: "Kuřecí řízky v pohankové strouhance",
    description: "Křupavé kuřecí řízky obalené v pohankové strouhance — bezlepková varianta klasiky.",
    mealTypes: "vecere,obed",
    ingredients: [
      { name: "Kuřecí prsa", amount: 400, unit: "g" },
      { name: "Pohankové kroupy (rozmixované)", amount: 80, unit: "g" },
      { name: "Vejce", amount: 2, unit: "ks" },
      { name: "Sůl, pepř", amount: 1, unit: "špetka" },
      { name: "Olej na smažení", amount: 50, unit: "ml" },
    ],
    instructions: [
      "Kuřecí prsa nakrájejte na plátky a rozklepejte.",
      "Osolte a opepřete.",
      "Namočte do rozšlehaného vejce, obalte v pohankové strouhance.",
      "Smažte na oleji 4–5 minut z každé strany dozlatova.",
      "Slijte na papírový ubrousek.",
    ],
    prepTime: 15,
    cookTime: 15,
    servings: 2,
    tags: "vecere,obed,bezlepkove",
  },
  {
    name: "Vepřový file s dušenou kapustou",
    description: "Šťavnatý vepřový file s jemně dušenou kapustou ochucenou kmínem.",
    mealTypes: "vecere,obed",
    ingredients: [
      { name: "Vepřový file (panenka)", amount: 400, unit: "g" },
      { name: "Kapusta hlávková", amount: 400, unit: "g" },
      { name: "Cibule", amount: 1, unit: "ks" },
      { name: "Máslo", amount: 20, unit: "g" },
      { name: "Kmín celý", amount: 0.5, unit: "lžičky" },
      { name: "Sůl", amount: 1, unit: "lžička" },
      { name: "Brambory", amount: 400, unit: "g" },
    ],
    instructions: [
      "Vepřový file nakrájejte na medailonky, osolte.",
      "Osmažte na másle 3–4 minuty z každé strany.",
      "Kapustu pokrájejte, orestujte s cibulí a kmínem.",
      "Přilijte 100 ml vody a duste 15 minut.",
      "Uvařte brambory.",
      "Podávejte maso s kapustou a bramborami.",
    ],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    tags: "vecere,obed,bezlepkove",
  },
  {
    name: "Lívance z tvarohu",
    description: "Jemné tvarohové lívance, výborné se zakysanou smetanou nebo medem.",
    mealTypes: "vecere,snidane",
    ingredients: [
      { name: "Tvaroh", amount: 250, unit: "g" },
      { name: "Vejce", amount: 2, unit: "ks" },
      { name: "Hladká mouka", amount: 80, unit: "g" },
      { name: "Cukr", amount: 2, unit: "lžíce" },
      { name: "Jedlá soda", amount: 0.5, unit: "lžičky" },
      { name: "Vanilkový extrakt", amount: 0.5, unit: "lžičky" },
      { name: "Olej na smažení", amount: 20, unit: "ml" },
      { name: "Med na podávání", amount: 2, unit: "lžíce" },
    ],
    instructions: [
      "Tvaroh, vejce, mouku, cukr, jedlou sodu a vanilku smíchejte dohladka.",
      "Nechte těsto 10 minut odpočinout.",
      "Na oleji smažte lívance — lžicí klaďte hromádky těsta.",
      "Smažte 2–3 minuty z každé strany, dokud nezbejdnou zlatavé.",
      "Podávejte s medem nebo javorovým sirupem.",
    ],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    tags: "vecere,snidane,vegetarianke",
  },
  {
    name: "Pstruh na másle s petrželí",
    description: "Čerstvý pstruh opečený na másle, podávaný s vařenými bramborami a petrželí.",
    mealTypes: "vecere,obed",
    ingredients: [
      { name: "Pstruh celý (čerstvý)", amount: 2, unit: "ks (cca 300 g každý)" },
      { name: "Máslo", amount: 40, unit: "g" },
      { name: "Česnek", amount: 2, unit: "stroužky" },
      { name: "Čerstvá petrželová nať", amount: 1, unit: "hrst" },
      { name: "Sůl", amount: 1, unit: "lžička" },
      { name: "Brambory", amount: 400, unit: "g" },
    ],
    instructions: [
      "Pstruhy omyjte, osušte, osolte zevnitř i zvenčí.",
      "Na pánvi rozpusťte máslo s česnekem.",
      "Smažte pstruhy 5–6 minut z každé strany.",
      "Mezitím uvařte brambory v osolené vodě.",
      "Podávejte posypané čerstvou petrželí.",
    ],
    prepTime: 10,
    cookTime: 20,
    servings: 2,
    tags: "vecere,obed,bezlepkove",
  },
  {
    name: "Rýžová zeleninová polévka s kuřecím masem",
    description: "Lehká a výživná polévka s rýží, zeleninou a kousky kuřecího masa.",
    mealTypes: "obed,vecere",
    ingredients: [
      { name: "Kuřecí prso", amount: 200, unit: "g" },
      { name: "Rýže kulatá", amount: 80, unit: "g" },
      { name: "Mrkev", amount: 2, unit: "ks" },
      { name: "Petržel kořen", amount: 1, unit: "ks" },
      { name: "Celer kořen", amount: 50, unit: "g" },
      { name: "Kuřecí vývar", amount: 1.2, unit: "l" },
      { name: "Petrželová nať", amount: 1, unit: "hrst" },
      { name: "Sůl", amount: 1, unit: "lžička" },
    ],
    instructions: [
      "Vývar přiveďte k varu.",
      "Kuřecí prso a zeleninu nakrájejte na kostičky.",
      "Přidejte do vývaru zeleninu a vařte 10 minut.",
      "Přidejte rýži a kuřecí maso.",
      "Vařte dalších 15 minut.",
      "Dosolte, podávejte posypané petrželí.",
    ],
    prepTime: 15,
    cookTime: 30,
    servings: 3,
    tags: "obed,vecere,polevka,bezlepkove",
  },
  {
    name: "Batátová polévka s kokosem",
    description: "Sladká krémová polévka z batátů s kokosovým mlékem.",
    mealTypes: "obed",
    ingredients: [
      { name: "Batáty", amount: 600, unit: "g" },
      { name: "Cibule", amount: 1, unit: "ks" },
      { name: "Kokosové mléko", amount: 200, unit: "ml" },
      { name: "Zeleninový vývar", amount: 600, unit: "ml" },
      { name: "Čerstvý zázvor", amount: 10, unit: "g" },
      { name: "Olivový olej", amount: 20, unit: "ml" },
      { name: "Sůl", amount: 1, unit: "lžička" },
    ],
    instructions: [
      "Batáty oloupejte a nakrájejte na kostky.",
      "Cibuli osmažte na oleji, přidejte zázvor a batáty.",
      "Zalijte vývarem a vařte 20 minut.",
      "Rozmixujte, přilijte kokosové mléko.",
      "Zahřejte, dosolte a podávejte.",
    ],
    prepTime: 10,
    cookTime: 25,
    servings: 3,
    tags: "obed,polevka,bezlepkove,vegetarianke",
  },
  // === SVAČINA ===
  {
    name: "Rýžové chlebíčky s máslem a medem",
    description: "Jednoduché rýžové chlebíčky s máslem a kapkou medu — rychlá svačinka.",
    mealTypes: "svacina",
    ingredients: [
      { name: "Rýžové chlebíčky", amount: 3, unit: "ks" },
      { name: "Máslo", amount: 15, unit: "g" },
      { name: "Med", amount: 1, unit: "lžička" },
    ],
    instructions: [
      "Rýžové chlebíčky potřete máslem.",
      "Pokapejte medem a ihned podávejte.",
    ],
    prepTime: 2,
    cookTime: 0,
    servings: 1,
    tags: "svacina,bezlepkove,rychle,studene",
  },
  {
    name: "Tvaroh s ovocem a granolou",
    description: "Osvěžující svačinka s tvarohem, čerstvým ovocem a křupavou granolou.",
    mealTypes: "svacina,snidane",
    ingredients: [
      { name: "Tvaroh jemný", amount: 150, unit: "g" },
      { name: "Jablko nebo hruška", amount: 1, unit: "ks" },
      { name: "Granola (bez ořechů)", amount: 30, unit: "g" },
      { name: "Med", amount: 1, unit: "lžička" },
    ],
    instructions: [
      "Ovoce oloupejte a nakrájejte.",
      "Do misky dejte tvaroh, přidejte ovoce.",
      "Posypte granolou a pokapejte medem.",
    ],
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    tags: "svacina,snidane,studene,rychle",
  },
  {
    name: "Pečené jablko s medem a skořicí (alternativa)",
    description: "Jemné pečené jablko — skořici vynechte nebo použijte ve velmi malém množství dle tolerance.",
    mealTypes: "svacina,dessert",
    ingredients: [
      { name: "Jablko", amount: 2, unit: "ks" },
      { name: "Med", amount: 2, unit: "lžičky" },
      { name: "Máslo", amount: 10, unit: "g" },
      { name: "Ovesné vločky", amount: 20, unit: "g" },
    ],
    instructions: [
      "Troubu předehřejte na 180 °C.",
      "Jablka oloupejte, odkrojte vrch a vydlabněte jádřinec.",
      "Naplňte medem, ovesnými vločkami a kouskem másla.",
      "Pečte 20 minut.",
      "Podávejte teplé.",
    ],
    prepTime: 10,
    cookTime: 20,
    servings: 2,
    tags: "svacina,dessert,bezlepkove,vegetarianke",
  },
  {
    name: "Rýžový nákyp s jablky",
    description: "Jemný rýžový nákyp se sladkými jablky, zapečený v troubě.",
    mealTypes: "svacina,dessert,snidane",
    ingredients: [
      { name: "Rýže kulatá", amount: 150, unit: "g" },
      { name: "Mléko", amount: 400, unit: "ml" },
      { name: "Jablka", amount: 2, unit: "ks" },
      { name: "Vejce", amount: 2, unit: "ks" },
      { name: "Cukr", amount: 3, unit: "lžíce" },
      { name: "Máslo", amount: 20, unit: "g" },
      { name: "Vanilkový extrakt", amount: 0.5, unit: "lžičky" },
    ],
    instructions: [
      "Rýži uvařte v mléce s cukrem a vanilkou (asi 20 minut), nechte mírně vychladnout.",
      "Jablka oloupejte a nakrájejte na plátky.",
      "Do rýže vmíchejte vejce.",
      "Formu na pečení vymažte máslem, naskládejte plátky jablek.",
      "Přelijte rýžovou kaší.",
      "Pečte při 180 °C 30 minut.",
    ],
    prepTime: 15,
    cookTime: 50,
    servings: 4,
    tags: "dessert,svacina,snidane,vegetarianke",
  },
  // === DEZERT ===
  {
    name: "Ovocný pohár s tvarohem",
    description: "Osvěžující dezert z vrstev tvarohu a čerstvého ovoce.",
    mealTypes: "dessert",
    ingredients: [
      { name: "Tvaroh jemný", amount: 200, unit: "g" },
      { name: "Mléko", amount: 50, unit: "ml" },
      { name: "Med", amount: 2, unit: "lžičky" },
      { name: "Jablko", amount: 1, unit: "ks" },
      { name: "Hruška", amount: 1, unit: "ks" },
      { name: "Borůvky", amount: 50, unit: "g" },
    ],
    instructions: [
      "Tvaroh rozmíchejte s mlékem a medem do hladka.",
      "Ovoce nakrájejte na kousky.",
      "Do pohárků skládejte střídavě vrstva tvarohu a vrstva ovoce.",
      "Navrch dejte borůvky.",
    ],
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    tags: "dessert,studene,bezlepkove,vegetarianke",
  },
  {
    name: "Pohankové sušenky s medem",
    description: "Jednoduché bezlepkové sušenky z pohankové mouky s medem.",
    mealTypes: "dessert,svacina",
    ingredients: [
      { name: "Pohankové mouky", amount: 150, unit: "g" },
      { name: "Máslo", amount: 60, unit: "g" },
      { name: "Med", amount: 40, unit: "g" },
      { name: "Vejce", amount: 1, unit: "ks" },
      { name: "Jedlá soda", amount: 0.25, unit: "lžičky" },
      { name: "Sůl", amount: 1, unit: "špetka" },
    ],
    instructions: [
      "Troubu předehřejte na 170 °C.",
      "Máslo s medem smíchejte dohladka.",
      "Přidejte vejce a promíchejte.",
      "Vmíchejte mouku, jedlou sodu a sůl.",
      "Z těsta tvarujte malé kuličky a poklaďte na plech s pečicím papírem.",
      "Pečte 12–14 minut dozlatova.",
    ],
    prepTime: 15,
    cookTime: 14,
    servings: 4,
    tags: "dessert,svacina,bezlepkove,vegetarianke",
  },
  {
    name: "Pečený banán (pro odolnější)",
    description: "Pečený banán s kapkou medu — banana je hraniční potravina, vyzkoušejte toleranci.",
    mealTypes: "dessert,svacina",
    ingredients: [
      { name: "Banány", amount: 2, unit: "ks" },
      { name: "Med", amount: 1, unit: "lžička" },
      { name: "Máslo", amount: 10, unit: "g" },
      { name: "Ovesné vločky", amount: 20, unit: "g" },
    ],
    instructions: [
      "Banány rozkrojte podélně.",
      "Dejte na pečicí papír, potřete máslem a polijte medem.",
      "Posypte ovesnými vločkami.",
      "Pečte 15 minut při 180 °C.",
    ],
    prepTime: 5,
    cookTime: 15,
    servings: 2,
    tags: "dessert,svacina,bezlepkove,vegetarianke,hranicni",
  },
  // === DALŠÍ RŮZNÉ RECEPTY ===
  {
    name: "Kuřecí polévka s nudlemi",
    description: "Tradiční kuřecí polévka s domácími nudlemi a zeleninou.",
    mealTypes: "obed",
    ingredients: [
      { name: "Kuřecí stehno bez kůže", amount: 400, unit: "g" },
      { name: "Mrkev", amount: 2, unit: "ks" },
      { name: "Petržel kořen", amount: 1, unit: "ks" },
      { name: "Celer kořen", amount: 50, unit: "g" },
      { name: "Cibule", amount: 1, unit: "ks" },
      { name: "Tenké nudle", amount: 80, unit: "g" },
      { name: "Petrželová nať", amount: 1, unit: "hrst" },
      { name: "Sůl", amount: 1, unit: "lžička" },
      { name: "Bobkový list", amount: 2, unit: "ks" },
    ],
    instructions: [
      "Kuřecí stehno zalijte studenou vodou (1,5 l) a pomalu přiveďte k varu.",
      "Sbírejte pěnu, přidejte celou zeleninu a koření.",
      "Vařte 60 minut.",
      "Maso vyjměte, zeleninu nakrájejte, maso strhejte na vlákna.",
      "Do čistého vývaru přidejte zeleninu a maso.",
      "Přidejte nudle a vařte 5 minut.",
      "Podávejte posypané petrželí.",
    ],
    prepTime: 15,
    cookTime: 70,
    servings: 4,
    tags: "obed,polevka",
  },
  {
    name: "Dušená kuřecí stehna s bramborami",
    description: "Měkká dušená kuřecí stehna s bramborami a mrkví v jemné omáčce.",
    mealTypes: "obed,vecere",
    ingredients: [
      { name: "Kuřecí stehna", amount: 600, unit: "g" },
      { name: "Brambory", amount: 500, unit: "g" },
      { name: "Mrkev", amount: 2, unit: "ks" },
      { name: "Cibule", amount: 1, unit: "ks" },
      { name: "Kuřecí vývar", amount: 200, unit: "ml" },
      { name: "Máslo", amount: 20, unit: "g" },
      { name: "Tymián", amount: 2, unit: "větvičky" },
      { name: "Sůl, pepř", amount: 1, unit: "špetka" },
    ],
    instructions: [
      "Stehna osolte a osmažte na másle dozlatova.",
      "Přidejte nakrájenou cibuli, brambory a mrkev.",
      "Zalijte vývarem, přidejte tymián.",
      "Duste pod pokličkou 40 minut.",
      "Podávejte s jídlem.",
    ],
    prepTime: 15,
    cookTime: 50,
    servings: 3,
    tags: "obed,vecere,bezlepkove",
  },
  {
    name: "Polenta s pečenou zeleninou",
    description: "Krémová polenta jako příloha nebo hlavní jídlo s pečenou zeleninou.",
    mealTypes: "obed,vecere",
    ingredients: [
      { name: "Kukuřičná krupice (polenta)", amount: 150, unit: "g" },
      { name: "Voda nebo vývar", amount: 600, unit: "ml" },
      { name: "Máslo", amount: 30, unit: "g" },
      { name: "Cuketa", amount: 1, unit: "ks" },
      { name: "Mrkev", amount: 2, unit: "ks" },
      { name: "Olivový olej", amount: 20, unit: "ml" },
      { name: "Sůl", amount: 1, unit: "lžička" },
      { name: "Čerstvá bazalka", amount: 1, unit: "hrst" },
    ],
    instructions: [
      "Zeleninu nakrájejte a pečte při 200 °C s olejem a solí 25 minut.",
      "Vodu nebo vývar přiveďte k varu, osolte.",
      "Za stálého míchání vsypávejte polentu.",
      "Míchejte 10 minut do zhoustnutí.",
      "Vmíchejte máslo.",
      "Podávejte polenta s pečenou zeleninou a bazalkou.",
    ],
    prepTime: 10,
    cookTime: 30,
    servings: 2,
    tags: "obed,vecere,bezlepkove,vegetarianke",
  },
  {
    name: "Kuřecí salát s hroznovým vínem a jablkem",
    description: "Lehký salát s vařeným kuřecím masem, ovocem a jemným jogurtovým dresinkem.",
    mealTypes: "obed",
    ingredients: [
      { name: "Vařené kuřecí prso", amount: 200, unit: "g" },
      { name: "Hroznové víno bílé", amount: 100, unit: "g" },
      { name: "Jablko", amount: 1, unit: "ks" },
      { name: "Salát ledový", amount: 100, unit: "g" },
      { name: "Tvaroh", amount: 80, unit: "g" },
      { name: "Mléko", amount: 30, unit: "ml" },
      { name: "Med", amount: 1, unit: "lžička" },
      { name: "Sůl, pepř", amount: 1, unit: "špetka" },
    ],
    instructions: [
      "Vařené kuřecí maso nakrájejte na kostičky.",
      "Jablko nakrájejte na kostičky, víno ponechte celé.",
      "Salát natrhejte.",
      "Dresink: tvaroh + mléko + med + sůl rozmíchejte dohladka.",
      "Vše smíchejte a polijte dresinkem.",
    ],
    prepTime: 15,
    cookTime: 0,
    servings: 2,
    tags: "obed,studene,bezlepkove",
  },
  {
    name: "Pečené kuřecí stehno s rýží a cuketou",
    description: "Pečené kuřecí stehno s bylinkovou marinádou, podávané s rýží a cuketou.",
    mealTypes: "obed,vecere",
    ingredients: [
      { name: "Kuřecí stehna", amount: 4, unit: "ks" },
      { name: "Rýže dlouhozrnná", amount: 200, unit: "g" },
      { name: "Cuketa", amount: 2, unit: "ks" },
      { name: "Olivový olej", amount: 30, unit: "ml" },
      { name: "Česnek", amount: 3, unit: "stroužky" },
      { name: "Rozmarýn, tymián", amount: 1, unit: "hrst" },
      { name: "Sůl, pepř", amount: 1, unit: "špetka" },
    ],
    instructions: [
      "Stehna potřete olivovým olejem smíchaným s česnekem a bylinkami.",
      "Marinujte 30 minut.",
      "Pečte v troubě při 190 °C 45 minut.",
      "Cuketu nakrájejte na kolečka a orestujte s česnekem.",
      "Uvařte rýži.",
      "Podávejte vše dohromady.",
    ],
    prepTime: 40,
    cookTime: 50,
    servings: 4,
    tags: "obed,vecere,bezlepkove",
  },
  {
    name: "Kukuřičná polévka",
    description: "Jemná krémová polévka z kukuřice.",
    mealTypes: "obed",
    ingredients: [
      { name: "Kukuřice (čerstvá nebo mražená)", amount: 400, unit: "g" },
      { name: "Brambory", amount: 2, unit: "ks" },
      { name: "Cibule", amount: 1, unit: "ks" },
      { name: "Máslo", amount: 20, unit: "g" },
      { name: "Zeleninový vývar", amount: 700, unit: "ml" },
      { name: "Mléko", amount: 100, unit: "ml" },
      { name: "Sůl, pepř", amount: 1, unit: "špetka" },
      { name: "Pažitka", amount: 10, unit: "g" },
    ],
    instructions: [
      "Cibuli osmažte na másle.",
      "Přidejte nakrájené brambory a kukuřici.",
      "Zalijte vývarem a vařte 20 minut.",
      "Přilijte mléko, rozmixujte.",
      "Dosolte a podávejte posypané pažitkou.",
    ],
    prepTime: 10,
    cookTime: 25,
    servings: 3,
    tags: "obed,polevka,bezlepkove,vegetarianke",
  },
  {
    name: "Těstoviny s máslem a šalvějí",
    description: "Jednoduché a rychlé těstoviny s rozpuštěným máslem a šalvějí.",
    mealTypes: "obed,vecere",
    ingredients: [
      { name: "Těstoviny (tagliatelle nebo fettuccine)", amount: 200, unit: "g" },
      { name: "Máslo", amount: 50, unit: "g" },
      { name: "Šalvěj čerstvá", amount: 8, unit: "listů" },
      { name: "Sůl, pepř", amount: 1, unit: "špetka" },
    ],
    instructions: [
      "Uvařte těstoviny v osolené vodě al dente.",
      "Na pánvi rozpusťte máslo, přidejte šalvěj a nechte zhnědnout.",
      "Slijte těstoviny, přidejte do másla.",
      "Promíchejte, dochuťte solí a pepřem.",
    ],
    prepTime: 5,
    cookTime: 12,
    servings: 2,
    tags: "obed,vecere,vegetarianke,rychle",
  },
  {
    name: "Cuketa plněná rýží a zeleninou",
    description: "Zapečená cuketa plněná rýží, zeleninou a jemným sýrem.",
    mealTypes: "obed,vecere",
    ingredients: [
      { name: "Cukety velké", amount: 2, unit: "ks" },
      { name: "Rýže vařená", amount: 150, unit: "g" },
      { name: "Mrkev", amount: 1, unit: "ks" },
      { name: "Cibule", amount: 0.5, unit: "ks" },
      { name: "Tvaroh nebo ricotta", amount: 100, unit: "g" },
      { name: "Olivový olej", amount: 20, unit: "ml" },
      { name: "Sůl, pepř", amount: 1, unit: "špetka" },
      { name: "Čerstvá bazalka", amount: 1, unit: "hrst" },
    ],
    instructions: [
      "Cukety podélně rozkrojte, vydlabejte dužinu.",
      "Dužinu nakrájejte na kostičky.",
      "Cibuli a mrkev orestujte na oleji, přidejte dužinu cukety.",
      "Smíchejte s rýží a tvarohem, osolte.",
      "Naplňte cukety, zalijte olejem.",
      "Pečte při 180 °C 25 minut.",
      "Podávejte s bazalkou.",
    ],
    prepTime: 20,
    cookTime: 30,
    servings: 2,
    tags: "obed,vecere,bezlepkove,vegetarianke",
  },
  {
    name: "Míchaná vejce se špenátem (čerstvý)",
    description: "Rychlé míchaná vejce s čerstvým špenátem — pozor, špenát je hraniční ingredience.",
    mealTypes: "snidane,vecere",
    ingredients: [
      { name: "Vejce", amount: 3, unit: "ks" },
      { name: "Čerstvý špenát (malé množství)", amount: 50, unit: "g" },
      { name: "Máslo", amount: 10, unit: "g" },
      { name: "Sůl", amount: 1, unit: "špetka" },
    ],
    instructions: [
      "Špenát krátce povadněte na másle.",
      "Přilijte rozšlehaná vejce.",
      "Míchejte do cremova.",
      "Osolte a podávejte.",
    ],
    prepTime: 5,
    cookTime: 5,
    servings: 1,
    tags: "snidane,vecere,bezlepkove,hranicni,rychle",
  },
  {
    name: "Dýňová polévka",
    description: "Jemná krémová polévka z hokkaido dýně s bylinkovou přílohiou.",
    mealTypes: "obed",
    ingredients: [
      { name: "Hokkaido dýně", amount: 700, unit: "g" },
      { name: "Cibule", amount: 1, unit: "ks" },
      { name: "Česnek", amount: 2, unit: "stroužky" },
      { name: "Zeleninový vývar", amount: 700, unit: "ml" },
      { name: "Kokosové mléko", amount: 100, unit: "ml" },
      { name: "Olivový olej", amount: 20, unit: "ml" },
      { name: "Sůl", amount: 1, unit: "lžička" },
      { name: "Čerstvý zázvor", amount: 10, unit: "g" },
    ],
    instructions: [
      "Dýni nakrájejte na kousky (s kůží nebo bez).",
      "Cibuli, česnek a zázvor osmažte na oleji.",
      "Přidejte dýni a vývar.",
      "Vařte 25 minut.",
      "Rozmixujte, přilijte kokosové mléko.",
      "Dosolte.",
    ],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    tags: "obed,polevka,bezlepkove,vegetarianke",
  },
  {
    name: "Bramborový salát bez majonézy",
    description: "Klasický bramborový salát s cibulí a hořčicí — bez majonézy a octa.",
    mealTypes: "obed,vecere",
    ingredients: [
      { name: "Brambory vařené", amount: 600, unit: "g" },
      { name: "Cibule červená", amount: 0.5, unit: "ks" },
      { name: "Olivový olej", amount: 40, unit: "ml" },
      { name: "Hořčice (malé množství dle tolerance)", amount: 1, unit: "lžička" },
      { name: "Čerstvá petrželová nať", amount: 1, unit: "hrst" },
      { name: "Sůl, pepř", amount: 1, unit: "špetka" },
    ],
    instructions: [
      "Vařené brambory nakrájejte na kousky.",
      "Cibuli nakrájejte na tenká kolečka.",
      "Dresink: olej + hořčice + sůl + pepř smíchejte.",
      "Přilijte dresink na brambory, přidejte cibuli a petrželku.",
      "Promíchejte a nechte 30 minut odležet.",
    ],
    prepTime: 15,
    cookTime: 20,
    servings: 3,
    tags: "obed,vecere,studene,bezlepkove,vegetarianke,hranicni",
  },
  {
    name: "Pečená mrkev s medem a tymiánem",
    description: "Jednoduché pečené mrkve jako příloha nebo lehká svačina.",
    mealTypes: "svacina,obed",
    ingredients: [
      { name: "Mrkev", amount: 400, unit: "g" },
      { name: "Med", amount: 2, unit: "lžičky" },
      { name: "Olivový olej", amount: 20, unit: "ml" },
      { name: "Tymián čerstvý", amount: 3, unit: "větvičky" },
      { name: "Sůl", amount: 0.5, unit: "lžičky" },
    ],
    instructions: [
      "Mrkev oloupejte a nakrájejte na tyčky.",
      "Smíchejte s olejem, medem, tymiánem a solí.",
      "Pečte při 200 °C 25 minut.",
    ],
    prepTime: 10,
    cookTime: 25,
    servings: 2,
    tags: "svacina,priloha,bezlepkove,vegetarianke",
  },
  {
    name: "Pohankový pilaf se zeleninou",
    description: "Výživný pohankový pilaf s kořenovou zeleninou a čerstvými bylinkami.",
    mealTypes: "obed,vecere",
    ingredients: [
      { name: "Pohankové kroupy", amount: 200, unit: "g" },
      { name: "Mrkev", amount: 2, unit: "ks" },
      { name: "Cibule", amount: 1, unit: "ks" },
      { name: "Petržel kořen", amount: 1, unit: "ks" },
      { name: "Máslo", amount: 20, unit: "g" },
      { name: "Zeleninový vývar", amount: 400, unit: "ml" },
      { name: "Sůl, pepř", amount: 1, unit: "špetka" },
      { name: "Čerstvá petrželová nať", amount: 1, unit: "hrst" },
    ],
    instructions: [
      "Na másle osmažte nakrájenou cibuli.",
      "Přidejte pohankové kroupy a orestujte 2 minuty.",
      "Přidejte nakrájenou zeleninu.",
      "Zalijte vývarem (dvojnásobek množství pohanky).",
      "Vařte pod pokličkou 15 minut.",
      "Servírujte s petrželí.",
    ],
    prepTime: 10,
    cookTime: 20,
    servings: 2,
    tags: "obed,vecere,bezlepkove,vegetarianke",
  },
  {
    name: "Rybí polévka z tresky",
    description: "Jemná rybí polévka z čerstvé tresky s brambory a zeleninou.",
    mealTypes: "obed",
    ingredients: [
      { name: "Treska čerstvá (filé)", amount: 400, unit: "g" },
      { name: "Brambory", amount: 300, unit: "g" },
      { name: "Mrkev", amount: 2, unit: "ks" },
      { name: "Petržel kořen", amount: 1, unit: "ks" },
      { name: "Cibule", amount: 1, unit: "ks" },
      { name: "Máslo", amount: 20, unit: "g" },
      { name: "Petrželová nať", amount: 1, unit: "hrst" },
      { name: "Sůl", amount: 1, unit: "lžička" },
      { name: "Bobkový list", amount: 1, unit: "ks" },
    ],
    instructions: [
      "Zeleninu a brambory nakrájejte na kostičky.",
      "Na másle osmažte cibuli.",
      "Přidejte zeleninu, zalijte 1 l vody.",
      "Vařte 15 minut, přidejte brambory, vařte dalších 10 minut.",
      "Přidejte nakrájenou tresku a bobkový list.",
      "Vařte 5–8 minut.",
      "Dosolte, podávejte s petrželí.",
    ],
    prepTime: 15,
    cookTime: 35,
    servings: 3,
    tags: "obed,polevka,bezlepkove",
  },
  {
    name: "Tvarohové koláčky bez mouky",
    description: "Bezmoučné tvarohové košíčky zapečené v troubě — jemné a vláčné.",
    mealTypes: "dessert,svacina",
    ingredients: [
      { name: "Tvaroh", amount: 300, unit: "g" },
      { name: "Vejce", amount: 3, unit: "ks" },
      { name: "Med", amount: 3, unit: "lžíce" },
      { name: "Škrob (kukuřičný)", amount: 20, unit: "g" },
      { name: "Vanilkový extrakt", amount: 1, unit: "lžička" },
      { name: "Máslo na formy", amount: 10, unit: "g" },
    ],
    instructions: [
      "Troubu předehřejte na 160 °C.",
      "Smíchejte tvaroh s vejci, medem, škrobem a vanilkou.",
      "Formy na muffiny vymažte máslem.",
      "Naplňte formy těstem.",
      "Pečte 25 minut, nechte vychladnout v troubě.",
    ],
    prepTime: 10,
    cookTime: 25,
    servings: 6,
    tags: "dessert,svacina,bezlepkove,vegetarianke",
  },
  {
    name: "Pečené kuřecí křídla s bylinkami",
    description: "Šťavnatá kuřecí křídla pečená s česnekem a čerstvými bylinkami.",
    mealTypes: "vecere,obed",
    ingredients: [
      { name: "Kuřecí křídla", amount: 800, unit: "g" },
      { name: "Olivový olej", amount: 40, unit: "ml" },
      { name: "Česnek", amount: 4, unit: "stroužky" },
      { name: "Rozmarýn", amount: 3, unit: "větvičky" },
      { name: "Tymián", amount: 3, unit: "větvičky" },
      { name: "Sůl, pepř", amount: 1, unit: "lžička" },
    ],
    instructions: [
      "Křídla smíchejte s olejem, prolisovaným česnekem, bylinkami, solí a pepřem.",
      "Marinujte 30 minut nebo přes noc v lednici.",
      "Rozložte na plech.",
      "Pečte při 210 °C 35–40 minut, jednou otočte.",
    ],
    prepTime: 35,
    cookTime: 40,
    servings: 3,
    tags: "vecere,obed,bezlepkove",
  },
  {
    name: "Jáhlová kaše s meruňkami",
    description: "Výživná kaše z prosa s meruňkami — meruňky jsou hraniční, sledujte toleranci.",
    mealTypes: "snidane",
    ingredients: [
      { name: "Jáhly", amount: 100, unit: "g" },
      { name: "Mléko", amount: 300, unit: "ml" },
      { name: "Voda", amount: 100, unit: "ml" },
      { name: "Čerstvé meruňky", amount: 3, unit: "ks" },
      { name: "Med", amount: 1, unit: "lžička" },
      { name: "Máslo", amount: 5, unit: "g" },
    ],
    instructions: [
      "Jáhly propláchněte horkou vodou.",
      "Vařte v mléce s vodou asi 20 minut na mírném ohni za stálého míchání.",
      "Meruňky nakrájejte na kousky a přidejte do kaše.",
      "Přidejte máslo a med, podávejte.",
    ],
    prepTime: 5,
    cookTime: 22,
    servings: 1,
    tags: "snidane,bezlepkove,vegetarianke,hranicni",
  },
  {
    name: "Grilovaný sýr halloumi se salátem",
    description: "Grilovaný sýr halloumi (čerstvý, ne zrající) s lehkým zeleninovým salátem.",
    mealTypes: "obed,vecere",
    ingredients: [
      { name: "Sýr halloumi", amount: 200, unit: "g" },
      { name: "Salát ledový", amount: 100, unit: "g" },
      { name: "Okurka", amount: 0.5, unit: "ks" },
      { name: "Olivový olej", amount: 20, unit: "ml" },
      { name: "Sůl, pepř", amount: 1, unit: "špetka" },
      { name: "Čerstvá máta", amount: 5, unit: "listů" },
    ],
    instructions: [
      "Halloumi nakrájejte na plátky 1 cm.",
      "Grilujte nebo smažte na suché pánvi 2 minuty z každé strany.",
      "Salát a okurku nakrájejte.",
      "Polijte olejem, osolte, opepřete.",
      "Podávejte sýr na salátu s mátou.",
    ],
    prepTime: 10,
    cookTime: 5,
    servings: 2,
    tags: "obed,vecere,bezlepkove,vegetarianke,rychle",
  },
];

async function main() {
  console.log("Seeding database with low-histamine Czech recipes...");

  for (const recipe of recipes) {
    const slug = slugify(recipe.name);
    await prisma.recipe.upsert({
      where: { slug },
      create: {
        name: recipe.name,
        slug,
        description: recipe.description,
        mealTypes: recipe.mealTypes,
        ingredients: JSON.stringify(recipe.ingredients),
        instructions: JSON.stringify(recipe.instructions),
        prepTime: recipe.prepTime,
        cookTime: recipe.cookTime,
        servings: recipe.servings,
        tags: recipe.tags,
      },
      update: {
        description: recipe.description,
        ingredients: JSON.stringify(recipe.ingredients),
        instructions: JSON.stringify(recipe.instructions),
        prepTime: recipe.prepTime,
        cookTime: recipe.cookTime,
        servings: recipe.servings,
        tags: recipe.tags,
      },
    });
  }

  // Seed ingredient safety reference
  const ingredients = [
    { name: "Kuřecí maso", histamineLevel: "SAFE", category: "maso", notes: "Vždy čerstvé nebo zmražené" },
    { name: "Krůtí maso", histamineLevel: "SAFE", category: "maso", notes: null },
    { name: "Jehněčí maso", histamineLevel: "SAFE", category: "maso", notes: null },
    { name: "Vepřové maso", histamineLevel: "SAFE", category: "maso", notes: "Čerstvé, ne uzené" },
    { name: "Telecí maso", histamineLevel: "SAFE", category: "maso", notes: null },
    { name: "Losos", histamineLevel: "MODERATE", category: "ryby", notes: "Pouze čerstvý nebo zmražený, připravit ihned" },
    { name: "Treska", histamineLevel: "SAFE", category: "ryby", notes: "Čerstvá nebo zmražená" },
    { name: "Pstruh", histamineLevel: "SAFE", category: "ryby", notes: "Čerstvý nebo zmražený" },
    { name: "Vejce", histamineLevel: "SAFE", category: "vejce", notes: "Bílek může být uvolňovač histaminu" },
    { name: "Rýže", histamineLevel: "SAFE", category: "obiloviny", notes: null },
    { name: "Pohanka", histamineLevel: "SAFE", category: "obiloviny", notes: null },
    { name: "Quinoa", histamineLevel: "SAFE", category: "obiloviny", notes: null },
    { name: "Jáhly", histamineLevel: "SAFE", category: "obiloviny", notes: null },
    { name: "Ovesné vločky", histamineLevel: "SAFE", category: "obiloviny", notes: null },
    { name: "Brambory", histamineLevel: "SAFE", category: "zelenina", notes: null },
    { name: "Mrkev", histamineLevel: "SAFE", category: "zelenina", notes: null },
    { name: "Cuketa", histamineLevel: "SAFE", category: "zelenina", notes: null },
    { name: "Brokolice", histamineLevel: "SAFE", category: "zelenina", notes: null },
    { name: "Květák", histamineLevel: "SAFE", category: "zelenina", notes: null },
    { name: "Kapusta", histamineLevel: "SAFE", category: "zelenina", notes: null },
    { name: "Salát ledový", histamineLevel: "SAFE", category: "zelenina", notes: null },
    { name: "Okurka", histamineLevel: "SAFE", category: "zelenina", notes: null },
    { name: "Pórek", histamineLevel: "SAFE", category: "zelenina", notes: null },
    { name: "Cibule", histamineLevel: "SAFE", category: "zelenina", notes: "Vařená bezpečná, syrová může dráždit" },
    { name: "Česnek", histamineLevel: "SAFE", category: "zelenina", notes: null },
    { name: "Špenát", histamineLevel: "AVOID", category: "zelenina", notes: "Vysoký obsah histaminu" },
    { name: "Rajče", histamineLevel: "AVOID", category: "zelenina", notes: "Uvolňovač histaminu" },
    { name: "Lilek", histamineLevel: "AVOID", category: "zelenina", notes: null },
    { name: "Avokádo", histamineLevel: "AVOID", category: "ovoce", notes: null },
    { name: "Jablko", histamineLevel: "SAFE", category: "ovoce", notes: null },
    { name: "Hruška", histamineLevel: "SAFE", category: "ovoce", notes: null },
    { name: "Borůvky", histamineLevel: "SAFE", category: "ovoce", notes: null },
    { name: "Meloun", histamineLevel: "SAFE", category: "ovoce", notes: null },
    { name: "Mango", histamineLevel: "SAFE", category: "ovoce", notes: null },
    { name: "Hroznové víno", histamineLevel: "SAFE", category: "ovoce", notes: null },
    { name: "Jahody", histamineLevel: "AVOID", category: "ovoce", notes: "Uvolňovač histaminu" },
    { name: "Kiwi", histamineLevel: "AVOID", category: "ovoce", notes: null },
    { name: "Ananas", histamineLevel: "AVOID", category: "ovoce", notes: null },
    { name: "Citrusy", histamineLevel: "AVOID", category: "ovoce", notes: "Pomeranče, citrony, grapefruit" },
    { name: "Máslo", histamineLevel: "SAFE", category: "tuky", notes: null },
    { name: "Olivový olej", histamineLevel: "SAFE", category: "tuky", notes: null },
    { name: "Kokosový olej", histamineLevel: "SAFE", category: "tuky", notes: null },
    { name: "Mléko", histamineLevel: "SAFE", category: "mlecne", notes: "Čerstvé pasterizované" },
    { name: "Tvaroh", histamineLevel: "SAFE", category: "mlecne", notes: "Čerstvý" },
    { name: "Ricotta", histamineLevel: "SAFE", category: "mlecne", notes: null },
    { name: "Zrající sýry", histamineLevel: "AVOID", category: "mlecne", notes: "Ementál, parmezán, čedar a další" },
    { name: "Jogurt", histamineLevel: "MODERATE", category: "mlecne", notes: "Fermentovaný – záleží na toleranci" },
    { name: "Kefír", histamineLevel: "AVOID", category: "mlecne", notes: "Fermentovaný výrobek" },
    { name: "Med", histamineLevel: "SAFE", category: "slazeni", notes: null },
    { name: "Javorový sirup", histamineLevel: "SAFE", category: "slazeni", notes: null },
    { name: "Alkohol", histamineLevel: "AVOID", category: "napoje", notes: "Veškerý alkohol" },
    { name: "Čokoláda", histamineLevel: "AVOID", category: "slazeni", notes: null },
    { name: "Vlašské ořechy", histamineLevel: "AVOID", category: "orisky", notes: null },
    { name: "Arašídy", histamineLevel: "AVOID", category: "orisky", notes: null },
    { name: "Mandle", histamineLevel: "MODERATE", category: "orisky", notes: "V malém množství obvykle tolerováno" },
    { name: "Skořice", histamineLevel: "AVOID", category: "koreni", notes: "Uvolňovač histaminu" },
    { name: "Petrželová nať", histamineLevel: "SAFE", category: "koreni", notes: null },
    { name: "Bazalka", histamineLevel: "SAFE", category: "koreni", notes: null },
    { name: "Tymián", histamineLevel: "SAFE", category: "koreni", notes: null },
    { name: "Rozmarýn", histamineLevel: "SAFE", category: "koreni", notes: null },
    { name: "Kopr", histamineLevel: "SAFE", category: "koreni", notes: null },
    { name: "Pažitka", histamineLevel: "SAFE", category: "koreni", notes: null },
  ];

  for (const ing of ingredients) {
    await prisma.ingredient.upsert({
      where: { name: ing.name },
      create: ing,
      update: ing,
    });
  }

  const count = await prisma.recipe.count();
  const ingCount = await prisma.ingredient.count();
  console.log(`✓ Seeded ${count} recipes and ${ingCount} ingredients.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
